<div class="row-fluid  content-heading title">
	<div class="span11 offset1">
		<h2>Présentation</h2>
	</div>
</div>
<div class="separator">
	<span></span>
</div>
<div class="row-fluid">
	<div class="span2">
		<img src="<?= $this->baseUrl('/img/nao.jpg');?>" alt="petit robot nao" title="NAO" class="nao"/>
	</div>
	<div class="span8">
		<p class="text-info">
			Bruno Maisonnier a fondé Aldebaran Robotics en 2005, société dédiée à la robotique humanoïde.
			<br />C'est de là que NAO est né !<br />
			Ce petit compagnon mesure près de 58 centimètres et pèse environ 5 kilogrammes, il peut parler,
			entendre,voir, interagir avec son environement.
			Il possède de multiples moteurs ainsi que quelques capteurs tel que :
		</p>
		<ul class="nav nav-list text-info">
			<li>Sonar</li>
			<li>Microphones</li>
			<li>Capteurs sensoriels</li>
			<li>Caméras</li>
		</ul><br />
		<p class="text-info">
			Tel qu'il est équipé il peut réaliser de nombreuses choses comme 
			parler, marcher, reconnaître des personnes, comprendre ce qu'on lui dit,
			conduire une voiture, jouer au golf, saisir des objets, lire le contenu des mails 
			d'une boîte mail, etc ...<br />
			Il peut être utiliser pour un but éducatif, faire apprendre à un enfant 
			les tables de multiplication par exemple.
		</p>
	</div>
</div>

<? //echo phpinfo();?>